### ISSUE TITLE
How to inject an event in the event bus after successfully handling the command?

### ISSUE THREAD

**Issue by josecelano** [prooph/service-bus#122]
Hi, I am using this package on one of my current projects and I usually inject events in the bus at the end of the method which is handling the command. After reading this post from @matthiasnoback:

http://php-and-symfony.matthiasnoback.nl/2015/01/collecting-events-and-the-events-aware-command-bus/

I think the event provider could be a good feature to add to the package. Maybe the package already contains a way to do that.

Anyway I think it's not a big problem becuase he said the database transaction is created by the command bus. I usually use a transaction manager inside the command handler, so I can trigger the event aftter the transaction.

I suppose If I ever need to execute different commands wrapped by a transaction I could create a new command with the only responsability of triggering all sucommands inside a database transaction.

**Comment by prolic** [comment]
Perhaps you are looking for something like this?

https://github.com/prolic/event-store-bus-bridge/blob/master/src/EventPublisher.php

**Comment by josecelano** [comment]
Yes, @prolic , thanks. Now I have to find out how to integrate them in my Laravel application. I am using your Laravel integration package but it is not being easy becuase for the time being I am only using service bus package and most samples are using Event Sourcing. I think prooph packages are a good tool even if you are not implementing Event Sourcing. I miss simpler samples only using service bus ;-). Maybe something like the TODO demo sample without using event sourcing.

**Comment by jeremyb** [comment]
Hi @prolic @josecelano,

I comment this issue because I'm facing the same problem. I would like to try prooph, especially the service-bus component, without all the event sourcing stuff.
I already have used SimpleBus/MessageBus and something I like a lot is collecting events from the command handler, like this: http://simplebus.github.io/MessageBus/doc/message_recorder.html.

Do you know if there's a way to handle events from the command handler?
I've tried to inject an EventBus in the command handler, but it doesn't seem to work.

**Comment by codeliner** [comment]
@jeremyb do you have a gist with example code of what your are trying? Injecting a read to use event bus in the command handler should work.

**Comment by josecelano** [comment]
Hi @jeremyb I am using the [Laravel package](https://github.com/prooph/laravel-package) and It's very easy to use. Here is a sample code from one of my command handlers:

```
<?php

// ...
use Prooph\ServiceBus\EventBus;

class CreateProjectCommandHandler
{
    /**
     * @var EventBus
     */
    private $eventBus;

    /**
     * CreateProjectCommandHandler constructor.
     * @param EventBus $eventBus
     */
    public function __construct(EventBus $eventBus))
    {
        $this->eventBus = $eventBus;
    }

    /**
     * @param CreateProjectCommand $createProjectCommand
     * @throws Exception
     */
    public function __invoke(CreateProjectCommand $createProjectCommand)
    {
        // ...
		
        $payload = array(
            'project_id' => $project->getId()->getValue(),
            'project_owner_id' => $project->getOwnerId(),
        );

        $projectWasCreated = ProjectWasCreated::fromArray([
            'message_name' => ProjectWasCreated::NAME,
            'uuid' => $this->uuidGenerator->uuid4(),
            'version' => 1,
            'created_at' => $this->clock->nowImmutable(),
            'payload' => $payload,
            'metadata' => []
        ]);

        $this->eventBus->dispatch($projectWasCreated);		
    }
}
```
But in fact, I remember I tried to instantiate the command and service bus directly and it was not easy, even taking a look at the Laravel Package. It's a very complex package with a lot of features. So I can not help you if you are not using the Laravel Package. But anyway you can tell us which concrete problem you have: you can not create the EventBus? The EventBus is not dispacthing the event to the listeners?

**Comment by jeremyb** [comment]
Ok, I solved my problem, it's was a wrong configuration :( Sorry for the inconvenience.

I'm doing something very similar to you @josecelano, injecting the EventBus in the command handler to dispatch a domain event manually.
My event listeners were not called because I added a listener through his FQCN like here: https://github.com/prooph/proophessor-do-symfony/blob/master/src/AppBundle/Resources/config/service_bus.yml#L50 with a service id it works well :)

BTW thanks for your quick replies @josecelano and @codeliner ;)
