### ISSUE TITLE
Add amqp message dispatcher

### ISSUE THREAD

**Issue by prolic** [prooph/service-bus#60]
I'll provide the adapter, when I have some time left.

**Comment by codeliner** [comment]
:+1: that sounds great

FYI: 
prooph/service-bus < v4.0 contained an interface for message dispatchers. Currently, all available message dispatchers still implement the interface because I had no time yet to adjust them. 
Since v4.0 an interface is no longer required as a message dispatcher can use `Prooph\Common\Messaging\MessageConverter` to translate messages to plain PHP arrays independently.

My plan is to adjust the existing message dispatchers to be `__invoke`able. So a message dispatcher can act as a `callable` message handler and no further plugins are needed to integrate the message dispatcher. 
In combination with the  [ServiceLocatorPlugin](https://github.com/prooph/service-bus/blob/master/docs/plugins.md#servicelocatorplugin) you are then able to lazy load a message dispatcher.

**Comment by prolic** [comment]
done with https://github.com/prooph/humus-amqp-producer
